package floria:plugins;

interface floria {
    variant any {
        null,
        integer(s64),
        unsigned-integer(u64),
        float(f64),
        boolean(bool),
        text(string),
        blob(list<u8>),
        nested-list(nested-list),
        nested-map(nested-map),
    }

    resource nested-list {
        constructor(values: list<any>);
        get: func() -> list<any>;
        length: func() -> u64;
    }

    resource nested-map {
        constructor(kv-pairs: list<tuple<any, any>>);
        get: func() -> list<tuple<any, any>>;
        length: func() -> u64;
    }

    variant kind {
        group,
        node-template,
        relationship-template,
        node,
        relationship,
    }

    record id {
        kind: kind,
        scope: list<string>,
        id: string,
    }

    log: func(source: string, message: string);
    get-entity: func(id: id) -> result<any, string>;
}

interface dispatch {
    variant any {
        null,
        integer(s64),
        unsigned-integer(u64),
        float(f64),
        boolean(bool),
        text(string),
        blob(list<u8>),
        nested-list(nested-list),
        nested-map(nested-map),
    }

    resource nested-list {
        constructor(values: list<any>);
        get: func() -> list<any>;
        length: func() -> u64;
    }

    resource nested-map {
        constructor(kv-pairs: list<tuple<any, any>>);
        get: func() -> list<tuple<any, any>>;
        length: func() -> u64;
    }

    variant kind {
        group,
        node-template,
        relationship-template,
        node,
        relationship,
    }

    record id {
        kind: kind,
        scope: list<string>,
        id: string,
    }

    record site {
        id: id,
        property-name: option<string>,
    }

    record error {
        name: string,
        arguments: list<string>,
        site: site,
        message: string,
    }

    dispatch: func(name: string, arguments: list<any>, site: site) -> result<any, error>;
}

world dispatch-plugin {
    import floria;
    export dispatch;
}
